test(upload): add upload tests
qmhc/vexip-ui pull request #116
Opened 2022-08-19 08:16 UTC by kev1nzh37

很不错的 Vue3 框架，新增了一些 Upload 组件的测试代码。

但是测试过程中发现很多有问题，想问下如果碰到问题，如何修复？提 issue，修复了再 pull 测试用例过来？

2022-08-19 08:24 UTC, qmhc commented
感谢贡献。

我的建议是，你可以把发现的问题发布对应 issue，然后将这个 PR 的范围扩大（只需要在评论中添加 fix #xxx 就可以自动关联 issue），涵盖这些 issue 以及测试用例的新增，那样就可以在一个 PR 下进行边测边修。

单元测试用例还在编写中，你可以关注 #102 的进度（Upload 是还未开始的），如果你打算为 Upload 单独编写测试，那 Upload 的进度我可以按这个 PR 为准。

2022-08-19 08:40 UTC, kev1nzh37 commented
感谢回复。

我会按照这样来完成 Upload 的测试。

2022-08-25 03:02 UTC, kev1nzh37 commented
除了 `on-preview`（发现个问题，似乎不能设置默认文件列表，不知道是设计成这样还是如何）、`on-drop`无法测试，其他应该都好了，有几个分支没测到。

2022-08-27 09:34 UTC, qmhc requested changes
目前整体上有几处需要改进的地方，见下方的评论。

除此之外有两个代码格式需要调整：一个是在每个 `it` 之间留一个空行，以维持排版的统一；另一个是清除所有的 `console` 语句。

然后是 `on-preview` 的问题，因为其用到了 `FileReader`，和 `xhr` 类似，我们需要根存一个模拟的对象，并模拟 `readAsDataURL` 方法，在该方法内将 `result` 属性为我们想要的 `Base64` 并调用 `this.onload`，因为在组件内部会像下面这样来使用 `FileReader`：

```ts
const reader = new FileReader()
reader.readAsDataURL(file.source)
reader.onload = () => {
  if (file.status !== UploadStatusType.DELETE) {
    file.base64 = reader.result?.toString() ?? null
  }
}
```

创建文件 `new File` 时只需要和往常一样，无需添加 `base64` 选项（加了也是无效的，而且会有 `ts` 错误）。

2022-08-27 09:34 UTC, qmhc commented on components/upload/tests/requests.spec.tsx
> +    await sleep(0)
这三个方法始终是一起执行的，我觉得应该将其整合成一个方法。

同时可以我觉得将名字描述成 `triggerUploadFiles` 或类似的意思更加语义化。

2022-08-27 09:34 UTC, qmhc commented on components/upload/tests/requests.spec.tsx
> +}
这个等待一个 minor 可以直接使用 vue 的 `nextTick`:

```ts
import { nextTick } from 'vue'

await nextTick()
```

2022-08-27 09:34 UTC, qmhc commented on components/upload/tests/requests.spec.tsx
> +        }
这个方法可以使用更简洁的写法：

```ts
const onChange = vi.fn()
const wrapper = mount(Upload, {
  props: {
    onChange
  }
})
```

2022-08-27 09:34 UTC, qmhc commented on components/upload/tests/requests.spec.tsx
> +    vi.stubGlobal('XMLHttpRequest', undefined)
这里可以使用 `afterEach` 进行简化：

```ts
import { afterEach } from 'vitest'

afterEach(() => {
  vi.stubGlobal('XMLHttpRequest', undefined)
})
```

2022-08-27 09:34 UTC, qmhc commented on components/upload/tests/upload.drag.spec.tsx
> +  })
这个测试可以直接整合至 `upload.spec.tsx` 中，无需单独一个文件。

2022-08-27 09:34 UTC, qmhc commented on components/upload/tests/upload.spec.tsx
> +  })
此处检查组件是否渲染正确，需要断言一下带有 css 变量的类名 `expect(wrapper.find('.vxp-upload).classes()).toContain('vxp-upload-vars')`。

同时作为可上传的组件最好再断言一下包含一个 `<input type="file">` (`disabled-click` 为特殊情况)。

2022-08-29 09:52 UTC, qmhc commented
我直接推送了一些修订的内容，现在你合并一下上游的主分支后，我即可合并这个 PR。

再次感谢你的贡献。

2022-09-06 01:26 UTC, qmhc approved these changes

2022-09-06 01:27 UTC, merged