feat(Viewer): add mirror flip function
qmhc/vexip-ui pull request #69
Opened 2022-07-02 19:32 UTC by orangelckc

fix #68

2022-07-02 19:33 UTC, orangelckc commented
这里的css浏览器适配，是否需要手动处理？

2022-07-03 02:36 UTC, qmhc commented
我们可能需要先讨论一下这个功能的实现。

翻转功能我们应该同时支持横向翻转和纵向翻转。

翻转相关的名称我们统一用 `flip`（尽量简短，特别是对外的属性设计上是尽可能的简短）指代。

包括 `filpDisabled`、`(F)filpHorizontal`、`(F)flipVertical`、`toggleFlipHorizontal`、`toggleFilpVertical`（只有正反两种情况的用 `toggle` 更符合语义）。

`ViewerState` 的拓展上，使用 `flipX` 和 `flipY`（对外用尽量简短的 `x/y` 指代方向）。
 
在图标的选择上，我认为 `Repeat` 这个图标更符合翻转这一行为：

<img src="https://user-images.githubusercontent.com/40221744/177021843-0ec702a1-794e-48c9-b207-1bd4f39b63b7.png" width="60" />

旋转 90° 后：

<img src="https://user-images.githubusercontent.com/40221744/177021834-7862730f-8555-4492-a7fb-a2324266a3b1.png" width="60" />

对于操作图标旋转，你可以在 `ToolbarAction` 拓展一个 `iconStyle` 来支持自定义的样式，或者直接添加一个 `iconProps` 并将 `iconScale` 整合进去以支持任意属性的设置。

`transform` 样式在线代浏览器没有适配问题。

2022-07-03 09:51 UTC, orangelckc commented
> 

明白，我尝试按这个做一下修改

2022-07-03 13:13 UTC, orangelckc commented
iconStyle 的样式这里不知道我理解的对不对，这么看着有点难受，看看怎么能优化一下？

2022-07-03 14:30 UTC, qmhc requested changes

2022-07-03 14:30 UTC, qmhc commented on components/viewer/symbol.ts
> +  iconStyle?: string | ((state: ViewerState) => string),
这里可以从 `@vexip-ui/config` 引入预定义好的 `StyleType` 作为样式的类型：

```ts
import type { StyleType } from '@vexip-ui/config'
```

2022-07-03 14:30 UTC, qmhc commented on components/viewer/viewer.vue
> +              :style="getActionProp(action,'iconStyle')"
此处注意一下 `,` 后未留有空格

2022-07-03 14:38 UTC, qmhc commented
我个人是更倾向使用 `iconProps` 来支持自定义配置 `Icon` 的属性的，类型定义如下：

```ts
import type { ClassType, StyleType } from '@vexip-ui/config'

interface IconProps {
  class?: ClassType,
  style?: StyleType,
  scale?: number,
  spin?: boolean | 'in' | 'out',
  pulse?: boolean | 'in' | 'out',
  flip?: 'horizontal' | 'vertical' | 'both'
}
```

不过可能这对于用户端的使用场景非常少，所以先以拓展 `iconStyle` 先支持内部使用我觉得也没有问题。

2022-07-03 14:53 UTC, orangelckc commented on components/viewer/viewer.vue
> +              :style="getActionProp(action,'iconStyle')"
好的，这里没注意，eslint也没发现
关于这里的scale我有个疑问，为什么要设置默认0，我看icon的默认scale是1，然后build的时候缩放到了0.85对吧

2022-07-03 14:58 UTC, qmhc commented on components/viewer/viewer.vue
> +              :style="getActionProp(action,'iconStyle')"
不好意思，我才发现，这是我的一个失误，`scale` 的默认值应该为 `1`，你可以同时改正这个问题。

2022-07-03 15:25 UTC, qmhc requested changes
刚刚有个地方没有看到，麻烦再跟进一下~

2022-07-03 15:25 UTC, qmhc commented on components/viewer/viewer.vue
> +        iconStyle: () => 'transform: rotate(90deg)',
~~这两个 `process` 无需接收额外参数，可以直接放方法本身，无需再包装一层函数~~；或者可以才参考 `toggleFull` 的形式，默认情况不传参的话去相反的状态，但也可以指定要切换到的状态，这可以允许用户通过 `ref` 使用组件方法时受控。

然后这里的 `style` 是一个静态值，不需要传递响应式依赖，所以无需使用函数来增加开销。

2022-07-03 20:23 UTC, orangelckc commented on components/viewer/viewer.vue
> +        iconStyle: () => 'transform: rotate(90deg)',
是的，按照`toggleFull`的形式会更友好
`style`目前内部使用静态就够了，这里后面如果需要用户自定义图标样式，我们再做修改

2022-07-04 01:30 UTC, qmhc approved these changes

2022-07-04 01:45 UTC, merged